"""Channel (TV) streaming server — continuous live HLS stream.

Serves a single continuous stream generated by :class:`ChannelMixer`.
The browser connects to the HLS manifest and receives a live TV-like
experience with scheduled series episodes and filler content between them.
"""

from __future__ import annotations

import logging
import time
import uuid
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any

from hometools.config import (
    get_channel_encoder,
    get_channel_filler_dir,
    get_channel_hls_dir,
    get_channel_schedule_file,
    get_channel_state_dir,
    get_video_library_dir,
)
from hometools.streaming.channel.mixer import ChannelMixer

logger = logging.getLogger(__name__)


def _render_channel_page(channel_name: str, hls_url: str) -> str:
    """Render the channel viewer HTML page with hls.js player + EPG."""
    return f"""<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>{channel_name}</title>
  <script src="https://cdn.jsdelivr.net/npm/hls.js@1/dist/hls.min.js"></script>
  <style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{ background: #121212; color: #e0e0e0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }}
    .container {{ max-width: 960px; margin: 0 auto; padding: 1rem; }}
    header {{
      display: flex; align-items: center; gap: 0.75rem;
      padding: 0.75rem 0; border-bottom: 1px solid #333; margin-bottom: 1rem;
    }}
    .channel-icon {{
      width: 36px; height: 36px; background: #7c4dff; border-radius: 8px;
      display: flex; align-items: center; justify-content: center;
      font-size: 1.2rem; flex-shrink: 0;
    }}
    header h1 {{ font-size: 1.1rem; font-weight: 600; }}
    .player-wrap {{
      position: relative; width: 100%; background: #000;
      border-radius: 10px; overflow: hidden; aspect-ratio: 16/9;
      cursor: pointer;
    }}
    video {{
      width: 100%; height: 100%; display: block;
      background: #000;
    }}
    /* ── Live-TV controls (no seekbar, no pause) ── */
    .tv-controls {{
      position: absolute; bottom: 0; left: 0; right: 0;
      display: flex; align-items: center; gap: 0.6rem;
      padding: 0.5rem 0.75rem;
      background: linear-gradient(transparent, rgba(0,0,0,.85));
      opacity: 0; transition: opacity .25s;
    }}
    .player-wrap:hover .tv-controls,
    .player-wrap.show-controls .tv-controls {{ opacity: 1; }}
    .tv-btn {{
      background: none; border: none; color: #fff; cursor: pointer;
      padding: 4px; display: flex; align-items: center;
    }}
    .tv-btn svg {{ width: 22px; height: 22px; fill: currentColor; }}
    .live-badge {{
      background: #f44336; color: #fff; font-size: 0.65rem; font-weight: 700;
      padding: 2px 7px; border-radius: 4px; letter-spacing: .04em;
      text-transform: uppercase; flex-shrink: 0; cursor: pointer;
      user-select: none;
    }}
    .live-badge.behind {{ background: #888; }}
    .tv-spacer {{ flex: 1; }}
    .tv-volume {{
      -webkit-appearance: none; appearance: none; width: 70px; height: 3px;
      background: rgba(255,255,255,.35); border-radius: 2px; outline: none;
      cursor: pointer;
    }}
    .tv-volume::-webkit-slider-thumb {{
      -webkit-appearance: none; width: 12px; height: 12px;
      border-radius: 50%; background: #fff; cursor: pointer;
    }}
    .now-playing {{
      background: #1e1e1e; border-radius: 10px; padding: 1rem;
      margin-top: 1rem; display: flex; align-items: center; gap: 1rem;
    }}
    .now-dot {{
      width: 10px; height: 10px; background: #f44336; border-radius: 50%;
      animation: pulse 1.5s ease-in-out infinite; flex-shrink: 0;
    }}
    @keyframes pulse {{ 0%,100% {{ opacity: 1; }} 50% {{ opacity: 0.4; }} }}
    .now-info {{ flex: 1; }}
    .now-series {{ font-weight: 600; font-size: 1rem; }}
    .now-episode {{ color: #aaa; font-size: 0.85rem; margin-top: 0.2rem; }}
    .now-filler {{ color: #888; font-style: italic; }}
    .epg {{ margin-top: 1.25rem; }}
    .epg-title {{
      font-size: 0.78rem; text-transform: uppercase; letter-spacing: .08em;
      color: #888; margin-bottom: 0.6rem;
    }}
    .epg-list {{ list-style: none; }}
    .epg-item {{
      display: flex; gap: 0.75rem; padding: 0.6rem 0;
      border-bottom: 1px solid #2a2a2a; font-size: 0.88rem;
    }}
    .epg-time {{ color: #7c4dff; font-weight: 600; flex-shrink: 0; width: 50px; }}
    .epg-series {{ color: #e0e0e0; }}
    .epg-episode {{ color: #888; margin-left: 0.4rem; }}
    .status-bar {{
      margin-top: 1.5rem; padding: 0.6rem; background: #1a1a1a;
      border-radius: 8px; font-size: 0.75rem; color: #666; text-align: center;
    }}
    .error-msg {{
      background: #2a1a1a; border: 1px solid #f44336; border-radius: 8px;
      padding: 1rem; margin-top: 1rem; color: #f44336; font-size: 0.9rem;
      display: none;
    }}
  </style>
</head>
<body>
  <div class="container">
    <header>
      <div class="channel-icon">📺</div>
      <h1>{channel_name}</h1>
    </header>

    <div class="player-wrap" id="player-wrap">
      <video id="player" autoplay playsinline muted></video>
      <div class="tv-controls">
        <span class="live-badge" id="live-badge" title="Zum Live-Signal springen">LIVE</span>
        <span class="tv-spacer"></span>
        <button class="tv-btn" id="btn-mute" title="Ton">
          <svg viewBox="0 0 24 24"><path id="vol-icon" d="M3 9v6h4l5 5V4L7 9H3zm13.5 3A4.5 4.5 0 0 0 14 8.3v7.4a4.47 4.47 0 0 0 2.5-3.7zM14 3.2v2.1a7 7 0 0 1 0 13.4v2.1A9 9 0 0 0 14 3.2z"/></svg>
        </button>
        <input type="range" class="tv-volume" id="vol-slider" min="0" max="1" step="0.05" value="0.8"/>
        <button class="tv-btn" id="btn-fs" title="Vollbild">
          <svg viewBox="0 0 24 24"><path d="M7 14H5v5h5v-2H7v-3zm-2-4h2V7h3V5H5v5zm12 7h-3v2h5v-5h-2v3zM14 5v2h3v3h2V5h-5z"/></svg>
        </button>
      </div>
    </div>

    <div id="error-msg" class="error-msg"></div>

    <div class="now-playing" id="now-playing">
      <div class="now-dot"></div>
      <div class="now-info">
        <div class="now-series" id="now-series">Verbinde...</div>
        <div class="now-episode" id="now-episode"></div>
      </div>
    </div>

    <div class="epg" id="epg-section">
      <div class="epg-title">Programm</div>
      <ul class="epg-list" id="epg-list"></ul>
    </div>

    <div class="status-bar" id="status-bar">
      Stream wird geladen...
    </div>
  </div>

  <script>
    var hlsUrl = '{hls_url}';
    var player = document.getElementById('player');
    var errorEl = document.getElementById('error-msg');
    var statusBar = document.getElementById('status-bar');
    var wrap = document.getElementById('player-wrap');
    var volIcon = document.getElementById('vol-icon');
    var volSlider = document.getElementById('vol-slider');
    var liveBadge = document.getElementById('live-badge');
    var _hideTimer = null;
    var _hls = null;
    var _errorCount = 0;

    /* ── Server session — detect server restarts ── */
    var _serverSession = hlsUrl.split('s=')[1] || '';
    function checkSession() {{
      fetch('/api/channel/session')
        .then(function(r) {{ return r.ok ? r.json() : null; }})
        .then(function(d) {{
          if (d && d.session && d.session !== _serverSession) {{
            /* Server was restarted — reload page to get fresh HLS URL */
            location.reload();
          }}
        }})
        .catch(function() {{}});
    }}
    setInterval(checkSession, 10000);

    /* ── Icon paths ── */
    var IC_VOL   = 'M3 9v6h4l5 5V4L7 9H3zm13.5 3A4.5 4.5 0 0 0 14 8.3v7.4a4.47 4.47 0 0 0 2.5-3.7zM14 3.2v2.1a7 7 0 0 1 0 13.4v2.1A9 9 0 0 0 14 3.2z';
    var IC_MUTE  = 'M16.5 12A4.5 4.5 0 0 0 14 8.3v1.5l2.4 2.4c.1-.2.1-.4.1-.7zm2.5 0a7 7 0 0 1-.6 2.8l1.5 1.5A9 9 0 0 0 21 12a9 9 0 0 0-7-8.8v2.1a7 7 0 0 1 5 6.7zM4.3 3L3 4.3 7.7 9H3v6h4l5 5v-6.7l4.3 4.3c-.7.5-1.4.9-2.3 1.1v2.1a9 9 0 0 0 3.9-1.8l2 2L21 20.3 4.3 3zM12 4l-2.1 2.1L12 8.3V4z';

    function syncIcons() {{
      volIcon.setAttribute('d', player.muted || player.volume === 0 ? IC_MUTE : IC_VOL);
    }}

    /* ── Jump to live edge (resets hls.js internal fragment queue) ── */
    function jumpToLive() {{
      if (_hls) {{
        /* startLoad(-1) tells hls.js to abandon all pending fragment loads
           and restart loading from the live edge of the manifest. */
        _hls.startLoad(-1);
      }}
      if (_hls && _hls.liveSyncPosition) {{
        player.currentTime = _hls.liveSyncPosition;
      }}
      liveBadge.classList.remove('behind');
      liveBadge.style.background = '#f44336';
      player.play().catch(function(){{}});
      _errorCount = 0;
    }}

    /* ── Controls visibility ── */
    function showControls() {{
      wrap.classList.add('show-controls');
      clearTimeout(_hideTimer);
      _hideTimer = setTimeout(function() {{ wrap.classList.remove('show-controls'); }}, 3000);
    }}
    wrap.addEventListener('mousemove', showControls);
    wrap.addEventListener('touchstart', showControls, {{passive:true}});

    /* ── Buttons ── */
    liveBadge.addEventListener('click', function(e) {{
      e.stopPropagation();
      jumpToLive();
    }});
    document.getElementById('btn-mute').addEventListener('click', function(e) {{
      e.stopPropagation();
      player.muted = !player.muted;
      syncIcons();
    }});
    volSlider.addEventListener('input', function() {{
      player.volume = parseFloat(this.value);
      player.muted = false;
      syncIcons();
    }});
    document.getElementById('btn-fs').addEventListener('click', function(e) {{
      e.stopPropagation();
      var el = wrap;
      if (document.fullscreenElement) {{ document.exitFullscreen(); }}
      else if (el.requestFullscreen) {{ el.requestFullscreen(); }}
      else if (el.webkitRequestFullscreen) {{ el.webkitRequestFullscreen(); }}
    }});
    /* Click on video area to unmute (first interaction) */
    wrap.addEventListener('click', function() {{
      if (player.muted) {{
        player.muted = false;
        player.volume = parseFloat(volSlider.value) || 0.8;
        syncIcons();
      }}
    }});
    player.addEventListener('volumechange', syncIcons);

    /* ── Detect if player falls behind live edge ── */
    function checkLiveEdge() {{
      if (!_hls || !_hls.liveSyncPosition) return;
      var behind = _hls.liveSyncPosition - player.currentTime;
      if (behind > 15) {{
        /* Too far behind — auto-jump to live */
        jumpToLive();
      }} else if (behind > 8) {{
        liveBadge.classList.add('behind');
      }} else {{
        liveBadge.classList.remove('behind');
      }}
    }}
    setInterval(checkLiveEdge, 2000);

    /* ── HLS setup — strict live-only mode ── */
    function startHls() {{
      if (_hls) {{
        _hls.destroy();
        _hls = null;
      }}
      _errorCount = 0;
      if (Hls.isSupported()) {{
        var hls = new Hls({{
          /* Strict live-edge tracking */
          liveSyncDurationCount: 3,
          liveMaxLatencyDurationCount: 5,
          liveDurationInfinity: true,
          enableWorker: true,
          lowLatencyMode: false,
          /* Minimal buffering — stay near live edge */
          maxBufferLength: 15,
          maxMaxBufferLength: 30,
          backBufferLength: 0,
          startFragPrefetch: true,
          /* Minimal retries — skip broken segments fast.
             With only 1 error retry, a 404 becomes fatal after 2 attempts.
             The fatal handler then restarts the whole HLS instance. */
          fragLoadPolicy: {{
            default: {{
              maxTimeToFirstByteMs: 8000,
              maxLoadTimeMs: 15000,
              timeoutRetry: {{ maxNumRetry: 1, retryDelayMs: 500, maxRetryDelayMs: 2000 }},
              errorRetry:   {{ maxNumRetry: 1, retryDelayMs: 500, maxRetryDelayMs: 1000 }},
            }},
          }},
          manifestLoadPolicy: {{
            default: {{
              maxTimeToFirstByteMs: 8000,
              maxLoadTimeMs: 15000,
              timeoutRetry: {{ maxNumRetry: 3, retryDelayMs: 500, maxRetryDelayMs: 2000 }},
              errorRetry:   {{ maxNumRetry: 3, retryDelayMs: 500, maxRetryDelayMs: 2000 }},
            }},
          }},
        }});
        _hls = hls;
        hls.loadSource(hlsUrl);
        hls.attachMedia(player);
        hls.on(Hls.Events.MANIFEST_PARSED, function() {{
          player.play().catch(function() {{}});
          statusBar.textContent = 'Live';
          liveBadge.style.display = '';
          _errorCount = 0;
        }});
        hls.on(Hls.Events.FRAG_LOADED, function() {{
          /* Successful fragment load — reset error counter */
          _errorCount = 0;
          liveBadge.classList.remove('behind');
          liveBadge.style.background = '#f44336';
          statusBar.textContent = 'Live';
          errorEl.style.display = 'none';
        }});
        hls.on(Hls.Events.ERROR, function(ev, data) {{
          if (!data.fatal) {{
            /* Non-fatal fragment error — use startLoad(-1) to reset the
               internal fragment queue and jump to the live edge.
               Simply setting player.currentTime does NOT clear the queue
               and hls.js keeps retrying the same broken segment. */
            if (data.details === 'fragLoadError' || data.details === 'fragLoadTimeOut') {{
              _errorCount++;
              if (_errorCount > 3) {{
                /* Too many consecutive errors — full restart */
                statusBar.textContent = 'Stream wird neu geladen...';
                liveBadge.classList.add('behind');
                setTimeout(function() {{ startHls(); }}, 2000);
              }} else {{
                jumpToLive();
              }}
            }}
            return;
          }}
          /* Fatal errors */
          if (data.type === Hls.ErrorTypes.MEDIA_ERROR) {{
            hls.recoverMediaError();
          }} else {{
            /* Network or other fatal error — full restart */
            statusBar.textContent = 'Verbindung unterbrochen — starte neu...';
            liveBadge.classList.add('behind');
            setTimeout(function() {{
              startHls();
            }}, 3000);
          }}
        }});
      }} else if (player.canPlayType('application/vnd.apple.mpegurl')) {{
        /* Native HLS (Safari / iOS) */
        player.src = hlsUrl;
        player.addEventListener('loadedmetadata', function() {{
          player.play().catch(function() {{}});
          statusBar.textContent = 'Live';
        }});
      }} else {{
        errorEl.textContent = 'HLS wird von diesem Browser nicht unterst\\u00fctzt.';
        errorEl.style.display = 'block';
      }}
    }}

    function updateNowPlaying() {{
      fetch('/api/channel/now')
        .then(function(r) {{ return r.ok ? r.json() : null; }})
        .then(function(d) {{
          if (!d) return;
          var seriesEl = document.getElementById('now-series');
          var epEl = document.getElementById('now-episode');
          if (d.is_filler) {{
            seriesEl.textContent = d.series === 'Sendepause' ? 'Sendepause' : 'Zwischenprogramm';
            seriesEl.classList.add('now-filler');
            epEl.textContent = d.episode || '';
          }} else {{
            seriesEl.textContent = d.series || 'Unbekannt';
            seriesEl.classList.remove('now-filler');
            epEl.textContent = d.episode || '';
          }}
        }})
        .catch(function() {{}});
    }}

    function updateEpg() {{
      fetch('/api/channel/epg')
        .then(function(r) {{ return r.ok ? r.json() : null; }})
        .then(function(d) {{
          if (!d || !d.items) return;
          var list = document.getElementById('epg-list');
          list.innerHTML = d.items.map(function(it) {{
            var t = it.start ? it.start.substring(11, 16) : '--:--';
            var cls = it.is_filler ? ' now-filler' : '';
            return '<li class="epg-item">'
              + '<span class="epg-time">' + t + '</span>'
              + '<span class="epg-series' + cls + '">' + (it.series || 'Filler') + '</span>'
              + '<span class="epg-episode">' + (it.episode || '') + '</span>'
              + '</li>';
          }}).join('');
        }})
        .catch(function() {{}});
    }}

    startHls();
    updateNowPlaying();
    updateEpg();
    syncIcons();
    setInterval(updateNowPlaying, 5000);
    setInterval(updateEpg, 30000);
  </script>
</body>
</html>"""


def create_app(
    library_dir: Path | None = None,
    *,
    schedule_file: Path | None = None,
    filler_dir: Path | None = None,
    hls_dir: Path | None = None,
) -> Any:
    """Create the FastAPI application for the channel (TV) server."""
    from fastapi import FastAPI, HTTPException
    from fastapi.responses import FileResponse, HTMLResponse

    resolved_library_dir = (library_dir or get_video_library_dir()).expanduser()
    resolved_schedule = (schedule_file or get_channel_schedule_file()).expanduser()
    resolved_filler_dir = (filler_dir or get_channel_filler_dir()).expanduser()
    resolved_hls_dir = (hls_dir or get_channel_hls_dir()).expanduser()
    resolved_state_dir = get_channel_state_dir()
    encoder = get_channel_encoder()

    # Read channel name from schedule
    channel_name = "Haus-TV"
    try:
        from hometools.streaming.channel.schedule import parse_schedule_file

        data = parse_schedule_file(resolved_schedule)
        channel_name = str(data.get("channel_name", channel_name))
    except Exception:
        pass

    mixer: ChannelMixer | None = None

    # Unique session ID — changes on every server restart.
    # Included in HLS URLs so stale browser tabs (from a previous server
    # session) are forced to reload the page rather than requesting old
    # segment numbers that no longer exist.
    server_session = uuid.uuid4().hex[:12]

    @asynccontextmanager
    async def lifespan(_app: FastAPI):
        nonlocal mixer

        startup_t0 = time.monotonic()
        logger.info(
            "Channel server startup: library=%s schedule=%s filler=%s encoder=%s",
            resolved_library_dir,
            resolved_schedule,
            resolved_filler_dir,
            encoder,
        )

        # Start the mixer in a background thread
        try:
            from hometools.streaming.channel.mixer import ChannelMixer as _MixerCls

            mixer = _MixerCls(
                schedule_file=resolved_schedule,
                library_dir=resolved_library_dir,
                filler_dir=resolved_filler_dir,
                hls_dir=resolved_hls_dir,
                state_dir=resolved_state_dir,
                encoder=encoder,
                channel_name=channel_name,
            )
            mixer.start()
        except Exception:
            logger.error("Failed to start ChannelMixer", exc_info=True)

        logger.info("Channel server startup complete in %.2fs", time.monotonic() - startup_t0)
        yield

        # Shutdown
        if mixer is not None:
            mixer.stop()
        logger.info("Channel server shutdown complete")

    app = FastAPI(title="hometools channel streaming", lifespan=lifespan)

    @app.get("/health")
    def health() -> dict[str, str]:
        mixer_running = mixer is not None and mixer.running if mixer else False
        return {
            "status": "ok" if mixer_running else "degraded",
            "library_dir": str(resolved_library_dir),
            "schedule_file": str(resolved_schedule),
            "mixer_running": str(mixer_running),
        }

    @app.get("/", response_class=HTMLResponse)
    def channel_home() -> HTMLResponse:
        return HTMLResponse(
            _render_channel_page(
                channel_name,
                f"/stream/channel.m3u8?s={server_session}",
            )
        )

    @app.get("/api/channel/session")
    def channel_session() -> dict[str, str]:
        """Return the current server session ID.

        The player polls this periodically.  If the session changes (server
        was restarted), the player reloads the page to get a fresh HLS URL.
        """
        return {"session": server_session}

    @app.get("/api/channel/now")
    def channel_now() -> dict[str, Any]:
        """What's currently playing."""
        if mixer is None:
            return {"series": "Offline", "episode": "", "is_filler": True}
        return mixer.get_now_playing()

    @app.get("/api/channel/epg")
    def channel_epg() -> dict[str, Any]:
        """Electronic Program Guide — upcoming slots."""
        if mixer is None:
            return {"items": []}
        return {"items": mixer.get_epg()}

    @app.get("/stream/channel.m3u8")
    def hls_manifest():
        """Serve the live HLS manifest.

        With the concat-demuxer architecture, a single ffmpeg process writes
        the manifest — it is always internally consistent.  A lightweight
        safety-net filter still removes references to segments that were
        already cleaned up by ``cleanup_segments()``.
        """
        from fastapi.responses import Response

        manifest = resolved_hls_dir / "channel.m3u8"
        if not manifest.exists():
            raise HTTPException(status_code=503, detail="Stream not ready — mixer is starting up")

        try:
            existing = {p.name for p in resolved_hls_dir.glob("channel_*.ts")}
            lines = manifest.read_text(encoding="utf-8").splitlines()
            clean: list[str] = []
            i = 0
            while i < len(lines):
                line = lines[i]
                if line.startswith("#EXTINF") and i + 1 < len(lines):
                    seg_line = lines[i + 1].strip()
                    if seg_line.endswith(".ts") and seg_line not in existing:
                        i += 2
                        continue
                if line.strip().endswith(".ts") and line.strip() not in existing:
                    i += 1
                    continue
                clean.append(line)
                i += 1

            return Response(
                content="\n".join(clean) + "\n",
                media_type="application/vnd.apple.mpegurl",
                headers={"Cache-Control": "no-cache, no-store"},
            )
        except Exception:
            logger.debug("Manifest filtering failed, serving raw", exc_info=True)
            return FileResponse(
                manifest,
                media_type="application/vnd.apple.mpegurl",
                headers={"Cache-Control": "no-cache, no-store"},
            )

    @app.get("/stream/{segment}")
    def hls_segment(segment: str):
        """Serve an HLS segment (.ts file)."""
        if not segment.endswith(".ts"):
            raise HTTPException(status_code=400, detail="Invalid segment name")
        seg_path = resolved_hls_dir / segment
        if not seg_path.exists():
            raise HTTPException(status_code=404, detail="Segment not found")
        return FileResponse(seg_path, media_type="video/mp2t")

    @app.get("/api/channel/schedule")
    def channel_schedule_raw() -> dict[str, Any]:
        """Return the raw schedule configuration."""
        from hometools.streaming.channel.schedule import parse_schedule_file

        data = parse_schedule_file(resolved_schedule)
        return {"schedule": data}

    return app
